/**
 * GitHub 存储服务 - 将灵感直接推送到 Obsidian 仓库
 */

class GithubService {
  constructor() {
    this.STORAGE_KEY = 'lifeos_github_config';
  }

  getConfig() {
    const data = localStorage.getItem(this.STORAGE_KEY);
    if (!data) return null;
    try {
      return JSON.parse(data);
    } catch (e) { return null; }
  }

  saveConfig(config) { localStorage.setItem(this.STORAGE_KEY, JSON.stringify(config)); }

  /**
   * 推送文件到 GitHub
   * @param {Object} data - 包含 title, content, type, status 等
   */
  async addRecord(data) {
    const config = this.getConfig();
    if (!config || !config.token || !config.repo) {
      throw new Error("请先配置 GitHub Token 和 仓库地址");
    }

    const { token, repo, branch = 'main', path = '选题管理/00-碎片想法' } = config;

    // 1. 准备文件名和路径
    const now = new Date();
    const timestamp = now.getTime();
    const dateStr = now.toISOString().split('T')[0];
    const fileName = `${dateStr}-${timestamp}.md`;
    const fullPath = `${path}/${fileName}`.replace(/\/+/g, '/');

    // 2. 构造 Markdown 内容 (符合 v2.1 规范)
    const markdownContent = `---
title: "${data.title || '无标题'}"
date: ${dateStr}
type: "${data.type || '灵感'}"
source: "${data.source || 'Life-OS'}"
status: "${data.status || 'inbox'}"
${data.direction ? `direction: "${data.direction}"` : ''}
${data.url ? `url: "${data.url}"` : ''}
---

${data.content || ''}

---
*Generated by Life-OS at ${now.toLocaleString()}*`;

    // 3. 检查内容大小 (GitHub API 限制 1MB)
    const contentSize = new Blob([markdownContent]).size;
    if (contentSize > 1024 * 1024) {
      throw new Error(`内容过大 (${(contentSize / 1024).toFixed(0)}KB)，GitHub API 限制为 1MB`);
    }

    const contentBase64 = btoa(unescape(encodeURIComponent(markdownContent)));

    // 4. 先检查文件是否已存在
    let sha = null;
    try {
      const checkResponse = await fetch(`https://api.github.com/repos/${repo}/contents/${fullPath}?ref=${branch}`, {
        headers: { 'Authorization': `token ${token}` }
      });
      if (checkResponse.ok) {
        const existingFile = await checkResponse.json();
        sha = existingFile.sha;
      }
    } catch (e) {
      // 文件不存在，继续创建新文件
    }

    // 5. 调用 GitHub API（带重试机制）
    const maxRetries = 3;
    let lastError;

    for (let attempt = 1; attempt <= maxRetries; attempt++) {
      try {
        const response = await fetch(`https://api.github.com/repos/${repo}/contents/${fullPath}`, {
          method: 'PUT',
          headers: {
            'Authorization': `token ${token}`,
            'Content-Type': 'application/json',
          },
          body: JSON.stringify({
            message: `Add new ${data.type || '灵感'} via Life-OS: ${data.title}`,
            content: contentBase64,
            branch: branch,
            sha: sha // 如果文件已存在，需要提供sha
          })
        });

        if (!response.ok) {
          const error = await response.json();

          // 详细的错误分类
          if (response.status === 401) {
            throw new Error("GitHub Token 无效或已过期，请重新配置");
          } else if (response.status === 403) {
            if (error.message && error.message.includes('rate limit')) {
              throw new Error("GitHub API 请求超限，请稍后再试");
            } else {
              throw new Error("GitHub Token 权限不足，需要 repo 权限");
            }
          } else if (response.status === 404) {
            throw new Error(`仓库或路径不存在: ${repo}/${fullPath}`);
          } else if (response.status === 422) {
            throw new Error(`验证失败: ${error.message}`);
          } else {
            throw new Error(`GitHub API Error (${response.status}): ${error.message || '未知错误'}`);
          }
        }

        return await response.json();

      } catch (error) {
        lastError = error;

        // 如果不是网络错误，直接抛出（不重试）
        if (!error.message.includes('fetch') && !error.message.includes('network')) {
          throw error;
        }

        // 最后一次尝试失败，抛出错误
        if (attempt === maxRetries) {
          throw new Error(`网络请求失败，已重试 ${maxRetries} 次: ${error.message}`);
        }

        // 等待后重试（指数退避）
        await new Promise(resolve => setTimeout(resolve, 1000 * Math.pow(2, attempt - 1)));
      }
    }

    throw lastError;
  }
}

const githubService = new GithubService();
export default githubService;
